name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  check-provenance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check provenance downgrades
        uses: danielroe/oidc-action
