name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  check-provenance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check provenance downgrades
        uses: danielroe/oidc-action@latest
        id: check
        with:
          lockfile: pnpm-lock.yaml # optional
          base-ref: origin/main    # optional, default: origin/main
          fail-on-downgrade: true  # optional, default: true
      - name: Print result
        run: "echo Downgraded ${{ steps.check.outputs.downgraded }}"
