name: ci

on:
  push:
    branches:
      - pnpm
      - npm
      - yarn
  pull_request:
    branches:
      - pnpm
      - npm
      - yarn
jobs:
  check-provenance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check provenance downgrades
        uses: danielroe/provenance-action@b8d91a9d9580e6d65f57b6b2e24175bfb9cf3d93
        with:
          base-ref: origin/npm
